//
//  DocumentViewModel.swift
//  SpeakApper.AI
//
//  Created by Nurtileu Amanzhol on 13.07.2025.
//

class DocumentViewModel {
    let privacyAndPolicy = DocumentForm(title: "Privacy Policy", version: "Version 1.0 — January 31, 2025", subtitles: ["1. Introduction", "2. Information We Collect", "3. How We Store and Secure Your Data", "4. Processing Your Data", "5. User Rights and Data Deletion", "6. Changes to This Privacy Policy", "7. Contact Information"], content: ["SpeakApper AI (\"we\", \"us\" or \"our\") is committed to protecting and respecting your privacy. This Privacy Policy explains how we collect, use, store, and disclose your personal information when you use our mobile application and website (collectively, \"SpeakApper AI\"). By using SpeakApper AI, you agree to the collection and use of your personal data as described in this Privacy Policy. If you do not agree, please discontinue use of the application immediately.", "We only collect data necessary for SpeakApper AI to function effectively as a speech-to-text transcription and AI text editing service. The data we collect includes: Basic Account Data: You can use SpeakApper AI without creating an account. In this case, a randomly generated user ID is assigned to you, which is not linked to any personal identifiable information. Optional Account Data: If you choose to create an account, we collect your name and email (Gmail) to store your recordings securely and sync your data across multiple devices. Your email is used solely for account recovery and authentication purposes. Audio Recordings: When you record audio using SpeakApper AI, we store those recordings along with their transcriptions in our database to allow access from multiple devices. Microphone Access: We require microphone permissions to enable voice recording functionality.", "All user data, including recordings and transcriptions, is stored in Firebase cloud storage.Currently, we do not apply encryption to stored audio recordings. However, we take standard security measures to protect your data from unauthorized access.", "SpeakApper AI relies on OpenAI API for speech-to-text transcription and AI-based text processing (e.g., summarization, rewriting). When you request a transcription, your audio data is sent to OpenAI’s servers for processing.OpenAI does not retain or use your data for any other purposes beyond providing the requested service.", "You have the right to access, correct, or erase your personal data.You can delete all stored recordings at any time by navigating to Settings > Data Management > Delete All Recordings within the app.You can delete your SpeakApper AI account, including all related data, in Settings > Account > Delete Account. Once deleted, your data cannot be recovered.", "If you have any questions about this Privacy Policy, please contact us at: support@speakapper.com"])
    
    let termsOfUsage = DocumentForm(title: "Terms of Service", version: "Version 1.0 — January 31, 2025", subtitles: ["1. Introduction", "2. Use of Services", "3. User Data & Privacy", "4. Intellectual Property", "5. Limitation of Liability", "6. Termination", "7. Changes to Terms", "8. Contact Information"], content: ["Welcome to SpeakApper AI! These Terms of Service (\"Terms\") govern your use of our mobile application and website (\"SpeakApper AI\"). By accessing or using SpeakApper AI, you agree to comply with these Terms. If you do not agree, please do not use our services.", "You must be at least 13 years old to use SpeakApper AI.You may use SpeakApper AI without an account or create an account for additional features.You agree to use SpeakApper AI only for lawful purposes and in compliance with all applicable laws.", "Your use of SpeakApper AI is also governed by our Privacy Policy, which describes how we collect, store, and process your data. By using our services, you consent to these practices.", "SpeakApper AI and all related materials, including but not limited to software, design, and content, are owned by us or our licensors. You may not reproduce, modify, or distribute any part of SpeakApper AI without our permission.By uploading content (e.g., audio recordings) to SpeakApper AI, you grant us a limited license to process and store the content for the purpose of providing transcription and related services.", "SpeakApper AI is provided \"as is\" without any warranties. We are not responsible for any loss or damage arising from your use of our services.We are not liable for any errors in transcriptions, loss of recordings, or any reliance on AI-generated outputs.", "We reserve the right to suspend or terminate your access to SpeakApper AI at our discretion, especially in cases of misuse, violation of these Terms, or security threats.", "We may update these Terms periodically. Continued use of SpeakApper AI after changes are posted constitutes acceptance of the revised Terms.", "If you have any questions regarding these Terms, please contact us at: support@speakapper.com"])
}
